# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='账户')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('old', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('grade', models.CharField(blank=True, max_length=64, null=True, verbose_name='班级')),
                ('head_img', models.ImageField(max_length=128, upload_to='imgs', verbose_name='照片')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户表',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='箱柜')),
                ('use_date', models.CharField(blank=True, max_length=64, null=True, verbose_name='开放时间')),
            ],
            options={
                'verbose_name': '箱柜表',
            },
        ),
        migrations.CreateModel(
            name='ChildBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='格子号')),
                ('status', models.SmallIntegerField(choices=[(0, '空闲'), (1, '预定')], default=0, verbose_name='当前状态')),
                ('boxnumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bag.Box', verbose_name='所属箱柜')),
            ],
            options={
                'verbose_name': '分柜表',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url_type', models.SmallIntegerField(choices=[(0, 'absolute'), (1, 'dynamic')], default=0)),
                ('url_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='ReservationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '审核中'), (1, '通过'), (2, '退订'), (3, '过期')], default=0, verbose_name='状态')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('Box', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bag.Box', verbose_name='箱柜')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bag.ChildBox', verbose_name='格子')),
            ],
            options={
                'verbose_name': '预约信息表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色')),
                ('menus', models.ManyToManyField(blank=True, to='bag.Menus', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='menus',
            unique_together=set([('name', 'url_name')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, default='', null=True, to='bag.Role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
